# These config values will be shared by all environments but can be overridden.
common: &common
  client_id: "app"

development:
  <<: *common
  brokers:
    - kafka:9092

test:
  <<: *common
  brokers:
    - kafka:9092

production:
  <<: *common
  brokers:
    - kafka:9092
